version: '3'

services:
    postgres:
        volumes:
            - /apps/amzjet/volumes/postgres:/var/lib/postgresql/data

    mongodb:
        volumes:
          - /apps/amzjet/volumes/mongodb:/data/db

    airflow:
        image: us.gcr.io/amplified-way-193307/amzjet/airflow-master
        volumes:
            # Mount local Secrets directory
            - /apps/amzjet/secrets/:/usr/local/airflow/secrets/

            # Mount Staging / Logs directories
            - /apps/amzjet/logs/airflow/:/usr/local/airflow/logs
            - /apps/amzjet/staging/airflow/:/usr/local/airflow/staging            
